name: Open-CE Feedstock PR Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  optional_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@1.7.0
        with:
          auto-update-conda: true
          python-version: "3.7"
      - uses: open-ce/open-ce/.github/actions/feedstock-optional-pr@master
  required_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ubuntu-latest
        with:
          fetch-depth: '0'
      - uses: conda-incubator/setup-miniconda@1.7.0
        with:
          auto-update-conda: true
          python-version: "3.7"
      - uses: open-ce/open-ce/.github/actions/feedstock-required-pr@master
